// World Cup 2026 Match Schedule
// Pre-populated from openfootball database
const WORLD_CUP_2026_MATCHES = [
  {
    "id": 1,
    "round": "Matchday 1",
    "date": "2026-06-11",
    "time": "13:00 UTC-6",
    "team1": "Mexico",
    "team2": "South Africa",
    "group": "Group A",
    "ground": "Mexico City",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 2,
    "round": "Matchday 1",
    "date": "2026-06-11",
    "time": "20:00 UTC-6",
    "team1": "South Korea",
    "team2": "Czech Republic",
    "group": "Group A",
    "ground": "Guadalajara (Zapopan)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 3,
    "round": "Matchday 8",
    "date": "2026-06-18",
    "time": "12:00 UTC-4",
    "team1": "Czech Republic",
    "team2": "South Africa",
    "group": "Group A",
    "ground": "Atlanta",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 4,
    "round": "Matchday 8",
    "date": "2026-06-18",
    "time": "19:00 UTC-6",
    "team1": "Mexico",
    "team2": "South Korea",
    "group": "Group A",
    "ground": "Guadalajara (Zapopan)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 5,
    "round": "Matchday 14",
    "date": "2026-06-24",
    "time": "19:00 UTC-6",
    "team1": "Czech Republic",
    "team2": "Mexico",
    "group": "Group A",
    "ground": "Mexico City",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 6,
    "round": "Matchday 14",
    "date": "2026-06-24",
    "time": "19:00 UTC-6",
    "team1": "South Africa",
    "team2": "South Korea",
    "group": "Group A",
    "ground": "Monterrey (Guadalupe)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 7,
    "round": "Matchday 2",
    "date": "2026-06-12",
    "time": "15:00 UTC-4",
    "team1": "Canada",
    "team2": "Bosnia & Herzegovina",
    "group": "Group B",
    "ground": "Toronto",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 8,
    "round": "Matchday 3",
    "date": "2026-06-13",
    "time": "12:00 UTC-7",
    "team1": "Qatar",
    "team2": "Switzerland",
    "group": "Group B",
    "ground": "San Francisco Bay Area (Santa Clara)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 9,
    "round": "Matchday 8",
    "date": "2026-06-18",
    "time": "12:00 UTC-7",
    "team1": "Switzerland",
    "team2": "Bosnia & Herzegovina",
    "group": "Group B",
    "ground": "Los Angeles (Inglewood)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 10,
    "round": "Matchday 8",
    "date": "2026-06-18",
    "time": "15:00 UTC-7",
    "team1": "Canada",
    "team2": "Qatar",
    "group": "Group B",
    "ground": "Vancouver",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 11,
    "round": "Matchday 14",
    "date": "2026-06-24",
    "time": "12:00 UTC-7",
    "team1": "Switzerland",
    "team2": "Canada",
    "group": "Group B",
    "ground": "Vancouver",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 12,
    "round": "Matchday 14",
    "date": "2026-06-24",
    "time": "12:00 UTC-7",
    "team1": "Bosnia & Herzegovina",
    "team2": "Qatar",
    "group": "Group B",
    "ground": "Seattle",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 13,
    "round": "Matchday 3",
    "date": "2026-06-13",
    "time": "18:00 UTC-4",
    "team1": "Brazil",
    "team2": "Morocco",
    "group": "Group C",
    "ground": "New York/New Jersey (East Rutherford)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 14,
    "round": "Matchday 3",
    "date": "2026-06-13",
    "time": "21:00 UTC-4",
    "team1": "Haiti",
    "team2": "Scotland",
    "group": "Group C",
    "ground": "Boston (Foxborough)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 15,
    "round": "Matchday 9",
    "date": "2026-06-19",
    "time": "18:00 UTC-4",
    "team1": "Scotland",
    "team2": "Morocco",
    "group": "Group C",
    "ground": "Boston (Foxborough)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 16,
    "round": "Matchday 9",
    "date": "2026-06-19",
    "time": "20:30 UTC-4",
    "team1": "Brazil",
    "team2": "Haiti",
    "group": "Group C",
    "ground": "Philadelphia",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 17,
    "round": "Matchday 14",
    "date": "2026-06-24",
    "time": "18:00 UTC-4",
    "team1": "Scotland",
    "team2": "Brazil",
    "group": "Group C",
    "ground": "Miami (Miami Gardens)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 18,
    "round": "Matchday 14",
    "date": "2026-06-24",
    "time": "18:00 UTC-4",
    "team1": "Morocco",
    "team2": "Haiti",
    "group": "Group C",
    "ground": "Atlanta",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 19,
    "round": "Matchday 2",
    "date": "2026-06-12",
    "time": "18:00 UTC-7",
    "team1": "USA",
    "team2": "Paraguay",
    "group": "Group D",
    "ground": "Los Angeles (Inglewood)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 20,
    "round": "Matchday 3",
    "date": "2026-06-13",
    "time": "21:00 UTC-7",
    "team1": "Australia",
    "team2": "Turkey",
    "group": "Group D",
    "ground": "Vancouver",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 21,
    "round": "Matchday 9",
    "date": "2026-06-19",
    "time": "12:00 UTC-7",
    "team1": "USA",
    "team2": "Australia",
    "group": "Group D",
    "ground": "Seattle",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 22,
    "round": "Matchday 9",
    "date": "2026-06-19",
    "time": "20:00 UTC-7",
    "team1": "Turkey",
    "team2": "Paraguay",
    "group": "Group D",
    "ground": "San Francisco Bay Area (Santa Clara)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 23,
    "round": "Matchday 15",
    "date": "2026-06-25",
    "time": "19:00 UTC-7",
    "team1": "Turkey",
    "team2": "USA",
    "group": "Group D",
    "ground": "Los Angeles (Inglewood)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 24,
    "round": "Matchday 15",
    "date": "2026-06-25",
    "time": "19:00 UTC-7",
    "team1": "Paraguay",
    "team2": "Australia",
    "group": "Group D",
    "ground": "San Francisco Bay Area (Santa Clara)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 25,
    "round": "Matchday 4",
    "date": "2026-06-14",
    "time": "12:00 UTC-5",
    "team1": "Germany",
    "team2": "Curaçao",
    "group": "Group E",
    "ground": "Houston",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 26,
    "round": "Matchday 4",
    "date": "2026-06-14",
    "time": "19:00 UTC-4",
    "team1": "Ivory Coast",
    "team2": "Ecuador",
    "group": "Group E",
    "ground": "Philadelphia",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 27,
    "round": "Matchday 10",
    "date": "2026-06-20",
    "time": "16:00 UTC-4",
    "team1": "Germany",
    "team2": "Ivory Coast",
    "group": "Group E",
    "ground": "Toronto",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 28,
    "round": "Matchday 10",
    "date": "2026-06-20",
    "time": "19:00 UTC-5",
    "team1": "Ecuador",
    "team2": "Curaçao",
    "group": "Group E",
    "ground": "Kansas City",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 29,
    "round": "Matchday 15",
    "date": "2026-06-25",
    "time": "16:00 UTC-4",
    "team1": "Curaçao",
    "team2": "Ivory Coast",
    "group": "Group E",
    "ground": "Philadelphia",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 30,
    "round": "Matchday 15",
    "date": "2026-06-25",
    "time": "16:00 UTC-4",
    "team1": "Ecuador",
    "team2": "Germany",
    "group": "Group E",
    "ground": "New York/New Jersey (East Rutherford)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 31,
    "round": "Matchday 4",
    "date": "2026-06-14",
    "time": "15:00 UTC-5",
    "team1": "Netherlands",
    "team2": "Japan",
    "group": "Group F",
    "ground": "Dallas (Arlington)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 32,
    "round": "Matchday 4",
    "date": "2026-06-14",
    "time": "20:00 UTC-6",
    "team1": "Sweden",
    "team2": "Tunisia",
    "group": "Group F",
    "ground": "Monterrey (Guadalupe)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 33,
    "round": "Matchday 10",
    "date": "2026-06-20",
    "time": "12:00 UTC-5",
    "team1": "Netherlands",
    "team2": "Sweden",
    "group": "Group F",
    "ground": "Houston",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 34,
    "round": "Matchday 10",
    "date": "2026-06-20",
    "time": "22:00 UTC-6",
    "team1": "Tunisia",
    "team2": "Japan",
    "group": "Group F",
    "ground": "Monterrey (Guadalupe)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 35,
    "round": "Matchday 15",
    "date": "2026-06-25",
    "time": "18:00 UTC-5",
    "team1": "Japan",
    "team2": "Sweden",
    "group": "Group F",
    "ground": "Dallas (Arlington)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 36,
    "round": "Matchday 15",
    "date": "2026-06-25",
    "time": "18:00 UTC-5",
    "team1": "Tunisia",
    "team2": "Netherlands",
    "group": "Group F",
    "ground": "Kansas City",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 37,
    "round": "Matchday 5",
    "date": "2026-06-15",
    "time": "12:00 UTC-7",
    "team1": "Belgium",
    "team2": "Egypt",
    "group": "Group G",
    "ground": "Seattle",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 38,
    "round": "Matchday 5",
    "date": "2026-06-15",
    "time": "18:00 UTC-7",
    "team1": "Iran",
    "team2": "New Zealand",
    "group": "Group G",
    "ground": "Los Angeles (Inglewood)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 39,
    "round": "Matchday 11",
    "date": "2026-06-21",
    "time": "12:00 UTC-7",
    "team1": "Belgium",
    "team2": "Iran",
    "group": "Group G",
    "ground": "Los Angeles (Inglewood)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 40,
    "round": "Matchday 11",
    "date": "2026-06-21",
    "time": "18:00 UTC-7",
    "team1": "New Zealand",
    "team2": "Egypt",
    "group": "Group G",
    "ground": "Vancouver",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 41,
    "round": "Matchday 16",
    "date": "2026-06-26",
    "time": "20:00 UTC-7",
    "team1": "Egypt",
    "team2": "Iran",
    "group": "Group G",
    "ground": "Seattle",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 42,
    "round": "Matchday 16",
    "date": "2026-06-26",
    "time": "20:00 UTC-7",
    "team1": "New Zealand",
    "team2": "Belgium",
    "group": "Group G",
    "ground": "Vancouver",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 43,
    "round": "Matchday 5",
    "date": "2026-06-15",
    "time": "12:00 UTC-4",
    "team1": "Spain",
    "team2": "Cape Verde",
    "group": "Group H",
    "ground": "Atlanta",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 44,
    "round": "Matchday 5",
    "date": "2026-06-15",
    "time": "18:00 UTC-4",
    "team1": "Saudi Arabia",
    "team2": "Uruguay",
    "group": "Group H",
    "ground": "Miami (Miami Gardens)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 45,
    "round": "Matchday 11",
    "date": "2026-06-21",
    "time": "12:00 UTC-4",
    "team1": "Spain",
    "team2": "Saudi Arabia",
    "group": "Group H",
    "ground": "Atlanta",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 46,
    "round": "Matchday 11",
    "date": "2026-06-21",
    "time": "18:00 UTC-4",
    "team1": "Uruguay",
    "team2": "Cape Verde",
    "group": "Group H",
    "ground": "Miami (Miami Gardens)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 47,
    "round": "Matchday 16",
    "date": "2026-06-26",
    "time": "19:00 UTC-5",
    "team1": "Cape Verde",
    "team2": "Saudi Arabia",
    "group": "Group H",
    "ground": "Houston",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 48,
    "round": "Matchday 16",
    "date": "2026-06-26",
    "time": "18:00 UTC-6",
    "team1": "Uruguay",
    "team2": "Spain",
    "group": "Group H",
    "ground": "Guadalajara (Zapopan)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 49,
    "round": "Matchday 6",
    "date": "2026-06-16",
    "time": "15:00 UTC-4",
    "team1": "France",
    "team2": "Senegal",
    "group": "Group I",
    "ground": "New York/New Jersey (East Rutherford)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 50,
    "round": "Matchday 6",
    "date": "2026-06-16",
    "time": "18:00 UTC-4",
    "team1": "Iraq",
    "team2": "Norway",
    "group": "Group I",
    "ground": "Boston (Foxborough)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 51,
    "round": "Matchday 12",
    "date": "2026-06-22",
    "time": "17:00 UTC-4",
    "team1": "France",
    "team2": "Iraq",
    "group": "Group I",
    "ground": "Philadelphia",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 52,
    "round": "Matchday 12",
    "date": "2026-06-22",
    "time": "20:00 UTC-4",
    "team1": "Norway",
    "team2": "Senegal",
    "group": "Group I",
    "ground": "New York/New Jersey (East Rutherford)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 53,
    "round": "Matchday 16",
    "date": "2026-06-26",
    "time": "15:00 UTC-4",
    "team1": "Norway",
    "team2": "France",
    "group": "Group I",
    "ground": "Boston (Foxborough)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 54,
    "round": "Matchday 16",
    "date": "2026-06-26",
    "time": "15:00 UTC-4",
    "team1": "Senegal",
    "team2": "Iraq",
    "group": "Group I",
    "ground": "Toronto",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 55,
    "round": "Matchday 6",
    "date": "2026-06-16",
    "time": "20:00 UTC-5",
    "team1": "Argentina",
    "team2": "Algeria",
    "group": "Group J",
    "ground": "Kansas City",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 56,
    "round": "Matchday 6",
    "date": "2026-06-16",
    "time": "21:00 UTC-7",
    "team1": "Austria",
    "team2": "Jordan",
    "group": "Group J",
    "ground": "San Francisco Bay Area (Santa Clara)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 57,
    "round": "Matchday 12",
    "date": "2026-06-22",
    "time": "12:00 UTC-5",
    "team1": "Argentina",
    "team2": "Austria",
    "group": "Group J",
    "ground": "Dallas (Arlington)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 58,
    "round": "Matchday 12",
    "date": "2026-06-22",
    "time": "20:00 UTC-7",
    "team1": "Jordan",
    "team2": "Algeria",
    "group": "Group J",
    "ground": "San Francisco Bay Area (Santa Clara)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 59,
    "round": "Matchday 17",
    "date": "2026-06-27",
    "time": "21:00 UTC-5",
    "team1": "Algeria",
    "team2": "Austria",
    "group": "Group J",
    "ground": "Kansas City",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 60,
    "round": "Matchday 17",
    "date": "2026-06-27",
    "time": "21:00 UTC-5",
    "team1": "Jordan",
    "team2": "Argentina",
    "group": "Group J",
    "ground": "Dallas (Arlington)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 61,
    "round": "Matchday 7",
    "date": "2026-06-17",
    "time": "12:00 UTC-5",
    "team1": "Portugal",
    "team2": "DR Congo",
    "group": "Group K",
    "ground": "Houston",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 62,
    "round": "Matchday 7",
    "date": "2026-06-17",
    "time": "20:00 UTC-6",
    "team1": "Uzbekistan",
    "team2": "Colombia",
    "group": "Group K",
    "ground": "Mexico City",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 63,
    "round": "Matchday 13",
    "date": "2026-06-23",
    "time": "12:00 UTC-5",
    "team1": "Portugal",
    "team2": "Uzbekistan",
    "group": "Group K",
    "ground": "Houston",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 64,
    "round": "Matchday 13",
    "date": "2026-06-23",
    "time": "20:00 UTC-6",
    "team1": "Colombia",
    "team2": "DR Congo",
    "group": "Group K",
    "ground": "Guadalajara (Zapopan)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 65,
    "round": "Matchday 17",
    "date": "2026-06-27",
    "time": "19:30 UTC-4",
    "team1": "Colombia",
    "team2": "Portugal",
    "group": "Group K",
    "ground": "Miami (Miami Gardens)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 66,
    "round": "Matchday 17",
    "date": "2026-06-27",
    "time": "19:30 UTC-4",
    "team1": "DR Congo",
    "team2": "Uzbekistan",
    "group": "Group K",
    "ground": "Atlanta",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 67,
    "round": "Matchday 7",
    "date": "2026-06-17",
    "time": "15:00 UTC-5",
    "team1": "England",
    "team2": "Croatia",
    "group": "Group L",
    "ground": "Dallas (Arlington)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 68,
    "round": "Matchday 7",
    "date": "2026-06-17",
    "time": "19:00 UTC-4",
    "team1": "Ghana",
    "team2": "Panama",
    "group": "Group L",
    "ground": "Toronto",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 69,
    "round": "Matchday 13",
    "date": "2026-06-23",
    "time": "16:00 UTC-4",
    "team1": "England",
    "team2": "Ghana",
    "group": "Group L",
    "ground": "Boston (Foxborough)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 70,
    "round": "Matchday 13",
    "date": "2026-06-23",
    "time": "19:00 UTC-4",
    "team1": "Panama",
    "team2": "Croatia",
    "group": "Group L",
    "ground": "Toronto",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 71,
    "round": "Matchday 17",
    "date": "2026-06-27",
    "time": "17:00 UTC-4",
    "team1": "Panama",
    "team2": "England",
    "group": "Group L",
    "ground": "New York/New Jersey (East Rutherford)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 72,
    "round": "Matchday 17",
    "date": "2026-06-27",
    "time": "17:00 UTC-4",
    "team1": "Croatia",
    "team2": "Ghana",
    "group": "Group L",
    "ground": "Philadelphia",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 73,
    "round": "Round of 32",
    "date": "2026-06-28",
    "time": "12:00 UTC-7",
    "team1": "2A",
    "team2": "2B",
    "group": "",
    "ground": "Los Angeles (Inglewood)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 74,
    "round": "Round of 32",
    "date": "2026-06-29",
    "time": "16:30 UTC-4",
    "team1": "1E",
    "team2": "3A/B/C/D/F",
    "group": "",
    "ground": "Boston (Foxborough)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 75,
    "round": "Round of 32",
    "date": "2026-06-29",
    "time": "19:00 UTC-6",
    "team1": "1F",
    "team2": "2C",
    "group": "",
    "ground": "Monterrey (Guadalupe)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 76,
    "round": "Round of 32",
    "date": "2026-06-29",
    "time": "12:00 UTC-5",
    "team1": "1C",
    "team2": "2F",
    "group": "",
    "ground": "Houston",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 77,
    "round": "Round of 32",
    "date": "2026-06-30",
    "time": "17:00 UTC-4",
    "team1": "1I",
    "team2": "3C/D/F/G/H",
    "group": "",
    "ground": "New York/New Jersey (East Rutherford)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 78,
    "round": "Round of 32",
    "date": "2026-06-30",
    "time": "12:00 UTC-5",
    "team1": "2E",
    "team2": "2I",
    "group": "",
    "ground": "Dallas (Arlington)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 79,
    "round": "Round of 32",
    "date": "2026-06-30",
    "time": "19:00 UTC-6",
    "team1": "1A",
    "team2": "3C/E/F/H/I",
    "group": "",
    "ground": "Mexico City",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 80,
    "round": "Round of 32",
    "date": "2026-07-01",
    "time": "12:00 UTC-4",
    "team1": "1L",
    "team2": "3E/H/I/J/K",
    "group": "",
    "ground": "Atlanta",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 81,
    "round": "Round of 32",
    "date": "2026-07-01",
    "time": "17:00 UTC-7",
    "team1": "1D",
    "team2": "3B/E/F/I/J",
    "group": "",
    "ground": "San Francisco Bay Area (Santa Clara)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 82,
    "round": "Round of 32",
    "date": "2026-07-01",
    "time": "13:00 UTC-7",
    "team1": "1G",
    "team2": "3A/E/H/I/J",
    "group": "",
    "ground": "Seattle",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 83,
    "round": "Round of 32",
    "date": "2026-07-02",
    "time": "19:00 UTC-4",
    "team1": "2K",
    "team2": "2L",
    "group": "",
    "ground": "Toronto",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 84,
    "round": "Round of 32",
    "date": "2026-07-02",
    "time": "12:00 UTC-7",
    "team1": "1H",
    "team2": "2J",
    "group": "",
    "ground": "Los Angeles (Inglewood)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 85,
    "round": "Round of 32",
    "date": "2026-07-02",
    "time": "20:00 UTC-7",
    "team1": "1B",
    "team2": "3E/F/G/I/J",
    "group": "",
    "ground": "Vancouver",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 86,
    "round": "Round of 32",
    "date": "2026-07-03",
    "time": "18:00 UTC-4",
    "team1": "1J",
    "team2": "2H",
    "group": "",
    "ground": "Miami (Miami Gardens)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 87,
    "round": "Round of 32",
    "date": "2026-07-03",
    "time": "20:30 UTC-5",
    "team1": "1K",
    "team2": "3D/E/I/J/L",
    "group": "",
    "ground": "Kansas City",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 88,
    "round": "Round of 32",
    "date": "2026-07-03",
    "time": "13:00 UTC-5",
    "team1": "2D",
    "team2": "2G",
    "group": "",
    "ground": "Dallas (Arlington)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 89,
    "round": "Round of 16",
    "date": "2026-07-04",
    "time": "17:00 UTC-4",
    "team1": "W74",
    "team2": "W77",
    "group": "",
    "ground": "Philadelphia",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 90,
    "round": "Round of 16",
    "date": "2026-07-04",
    "time": "12:00 UTC-5",
    "team1": "W73",
    "team2": "W75",
    "group": "",
    "ground": "Houston",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 91,
    "round": "Round of 16",
    "date": "2026-07-05",
    "time": "16:00 UTC-4",
    "team1": "W76",
    "team2": "W78",
    "group": "",
    "ground": "New York/New Jersey (East Rutherford)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 92,
    "round": "Round of 16",
    "date": "2026-07-05",
    "time": "18:00 UTC-6",
    "team1": "W79",
    "team2": "W80",
    "group": "",
    "ground": "Mexico City",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 93,
    "round": "Round of 16",
    "date": "2026-07-06",
    "time": "14:00 UTC-5",
    "team1": "W83",
    "team2": "W84",
    "group": "",
    "ground": "Dallas (Arlington)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 94,
    "round": "Round of 16",
    "date": "2026-07-06",
    "time": "17:00 UTC-7",
    "team1": "W81",
    "team2": "W82",
    "group": "",
    "ground": "Seattle",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 95,
    "round": "Round of 16",
    "date": "2026-07-07",
    "time": "12:00 UTC-4",
    "team1": "W86",
    "team2": "W88",
    "group": "",
    "ground": "Atlanta",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 96,
    "round": "Round of 16",
    "date": "2026-07-07",
    "time": "13:00 UTC-7",
    "team1": "W85",
    "team2": "W87",
    "group": "",
    "ground": "Vancouver",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 97,
    "round": "Quarter-final",
    "date": "2026-07-09",
    "time": "16:00 UTC-4",
    "team1": "W89",
    "team2": "W90",
    "group": "",
    "ground": "Boston (Foxborough)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 98,
    "round": "Quarter-final",
    "date": "2026-07-10",
    "time": "12:00 UTC-7",
    "team1": "W93",
    "team2": "W94",
    "group": "",
    "ground": "Los Angeles (Inglewood)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 99,
    "round": "Quarter-final",
    "date": "2026-07-11",
    "time": "17:00 UTC-4",
    "team1": "W91",
    "team2": "W92",
    "group": "",
    "ground": "Miami (Miami Gardens)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 100,
    "round": "Quarter-final",
    "date": "2026-07-11",
    "time": "20:00 UTC-5",
    "team1": "W95",
    "team2": "W96",
    "group": "",
    "ground": "Kansas City",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 101,
    "round": "Semi-final",
    "date": "2026-07-14",
    "time": "14:00 UTC-5",
    "team1": "W97",
    "team2": "W98",
    "group": "",
    "ground": "Dallas (Arlington)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 102,
    "round": "Semi-final",
    "date": "2026-07-15",
    "time": "15:00 UTC-4",
    "team1": "W99",
    "team2": "W100",
    "group": "",
    "ground": "Atlanta",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 103,
    "round": "Match for third place",
    "date": "2026-07-18",
    "time": "17:00 UTC-4",
    "team1": "L101",
    "team2": "L102",
    "group": "",
    "ground": "Miami (Miami Gardens)",
    "goals1": null,
    "goals2": null
  },
  {
    "id": 104,
    "round": "Final",
    "date": "2026-07-19",
    "time": "15:00 UTC-4",
    "team1": "W101",
    "team2": "W102",
    "group": "",
    "ground": "New York/New Jersey (East Rutherford)",
    "goals1": null,
    "goals2": null
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = WORLD_CUP_2026_MATCHES;
}
